[tool.black]
line-length = 88

[tool.poetry.group.dev.dependencies]
black = "^25.9.0"

[project]
name = "telegram-loyalty-program-bot"
version = "0.1.0"
description = "Telegram bot with profile and loyalty program for offline shops"
authors = [
    {name = "Echways",email = "Echways@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiogram (>=3.22.0,<4.0.0)",
    "asyncio (>=4.0.0,<5.0.0)",
    "asyncpg (>=0.30.0,<0.31.0)",
    "sqlalchemy (>=2.0.43,<3.0.0)",
    "pydantic (>=2.11.9,<3.0.0)",
    "pathlib (>=1.0.1,<2.0.0)",
    "alembic (>=1.16.5,<2.0.0)",
    "pydantic-settings (>=2.11.0,<3.0.0)",
    "redis (>=6.4.0,<7.0.0)",
    "ruff (>=0.13.2,<0.14.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
package-mode = false
