"""create users table

Revision ID: 06042afef775
Revises: 2e94348936c2
Create Date: 2025-09-15 20:43:48.437491

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "06042afef775"
down_revision = "2e94348936c2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("tg_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column(
            "bonus_points", sa.Integer(), nullable=False, server_default=sa.text("0")
        ),
        sa.Column(
            "rank_points", sa.Integer(), nullable=False, server_default=sa.text("0")
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # уникальный индекс на tg_id
    op.create_index("ix_users_tg_id", "users", ["tg_id"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_users_tg_id", table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
